name: ✨ Feature Request
description: Suggest a new idea or feature for the ALIZARIN Engine.
title: "[FEAT] - "
labels: ["enhancement", "community-goal"]
body:
  - type: markdown
    attributes:
      value: "Have a great idea? We'd love to hear it. Please check our Roadmap first to see if it's already planned."
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: "A clear description of the problem. (e.g., 'I find it difficult to...')"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
